
server:
  port: ${PORT:8081}

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: "list-keep"
  resource: "list-keep"
  bearer-only: true
  security-constraints:
    - authRoles:
        - uma_authorization
      securityCollections:
        - patterns:
            - /api/*
  cors: false